# -*- coding: utf-8 -*-
"""ECT_HW3_104403553_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16S65qIUYuJGX2LonvXrCax2VBMKXcc0L

安裝efficient-apriori 用colab做的
"""

!pip install apyori
!pip install efficient-apriori

"""唯一有用到的就是 efficient_apriori"""

import pandas as pd
from efficient_apriori import apriori
from efficient_apriori import itemsets_from_transactions, generate_rules_apriori
import apyori

"""# **Implementation using Apyori**
不會動
"""

data = pd.read_csv('CreditCardPromotion.csv')
print(data)

apy_data = pd.read_csv('CreditCardPromotion.csv', header=None) 
print(apy_data)

apy_data.values.tolist()

#from apyori import load_transactions, apriori

#with open('CreditCardPromotion.csv') as f:
   # transactions = apyori.load_transactions(f)
   # results = list(apriori(transactions)

association_rules = (list(apyori.apriori(apy_data, min_support=0.9, min_confidence=0.2, min_lift=3, min_length=2)))

print(association_rules)

#association_results = list(association_rules)

"""# implementation using efficient_**apriori**
將csv擋讀近來，然後套到apriori的function裡面<br>
需要註明min_support跟min_confidence
下一步在印出來
"""

def data_generator(filename):
  
  def data_gen():
    with open(filename) as file:
      for line in file:
        yield tuple(k.strip() for k in line.split(',')) 
  
  return data_gen



csvfile_processed = data_generator('CreditCardPromotion.csv')
itemsets, rules = apriori(csvfile_processed, min_support=0.2, min_confidence=0.9,verbosity =2)
#itemsets,_ = itemsets_from_transactions(csvfile_processed,min_support=0.2)
#print(itemsets)
#list(generate_rules_apriori(itemsets, 1.0, 10))

print(itemsets)

print(rules)



